# Generated by Django 6.0.5 on 2026-06-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSplitter', '0002_group_created_at_group_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
