# Generated by Django 6.0.5 on 2026-06-16 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSplitter', '0003_alter_expense_created_at_alter_expense_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to='ExpenseSplitter.user'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_by', to='ExpenseSplitter.user'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='skipped_member',
            field=models.ManyToManyField(related_name='skipped_members', to='ExpenseSplitter.user'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expenses', to='ExpenseSplitter.user'),
        ),
        migrations.AlterField(
            model_name='expensesplit',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='ExpenseSplitter.user'),
        ),
        migrations.AlterField(
            model_name='expensesplit',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='ExpenseSplitter.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to='ExpenseSplitter.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', to='ExpenseSplitter.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
